CREATE TABLE dbo.VLFInfo(
	[DBName] [sysname] COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[NumOfVLFs] [int] NOT NULL,
	[ActiveVLFs] [int] NOT NULL,
	[RecoveryMode] [varchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[LogSizeMB] [int] NOT NULL,
	[LastUpdateTime] [datetime] NOT NULL CONSTRAINT [DF_TLogVLFInfo_LastUpdateTime] DEFAULT (getdate()),
	CONSTRAINT [PK_DBName] PRIMARY KEY CLUSTERED 
(
	[DBName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) 
) 
GO
 
CREATE NONCLUSTERED INDEX [IX_LogSizeMB] ON dbo.[VLFInfo]
(
	[LogSizeMB] ASC
)
INCLUDE ([NumOfVLFs]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) 
GO